[CONFIG]
dbAddress=sf.tascorp.co.kr
dbId=VL8beHOCRrrgfMNJv4Re4A==
dbPw=UL6Fh5zKurLmhb3qESaFlrlmvTjnX3AqYkRFhUpzwhQ=
dbName=RTEGMS_GREEN
reportServer=
plantCD=PC001
; DB 선택 룩업 visible 조정
serverYN=Y
; 사업장 선택 룩업 visible
plantYN=Y
position=700